seguridad/Controllers/ModuloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ET;
using seguridad.Filters;

namespace seguridad.Controllers
{
    
    public class ModuloController : Controller
    {
        ModuloContext moduloContext = new ModuloContext();

        //
        // GET: /Modulo/
        [CustomAuthorize("009")]
        public ActionResult Index()
        {
            List<Modulo> Modulos=moduloContext.Select(); ;
            //if (FilterAuth.Authorize_User("seguridad"))
            //{
            //    Modulos = moduloContext.Select();
            //}
            //else
            //{
            //    Modulos = moduloContext.selectFiltro("'seguridad'");
            //}

            if (TempData["Message"] != null)
            {
                ViewData["Message"] = TempData["Message"];
            }
            else
            {
                ViewData["Message"] = null;
            }

            return View(Modulos);
        }

        //
        // GET: /Modulo/Details/5
        [CustomAuthorize("009")]
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Modulo/Create
        [CustomAuthorize("005")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Modulo/Create

        [HttpPost]
        [CustomAuthorize("005")]
        public ActionResult Create(Modulo modulo)
        {
            var UserName = User.Identity.Name;
            try
            {
                if (ModelState.IsValid)
                {
                    moduloContext.Insert(modulo, UserName);
                    TempData["Message"] = "Creado Correctamente";

                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View();
        }

        //
        // GET: /Modulo/Edit/5
        [CustomAuthorize("007")]
        public ActionResult Edit(int id)
        {
            List<Modulo> Modulos = moduloContext.Select(
                    new Dictionary<string, string> { {"Modulo_Id", id.ToString()} }
                );
            return View(Modulos[0]);
        }

        //
        // POST: /Modulo/Edit/5

        [HttpPost]
        [CustomAuthorize("007")]
        public ActionResult Edit(Modulo modulo)
        {
            var UserName = User.Identity.Name;
            try
            {
                if (ModelState.IsValid){
                    moduloContext.Update(modulo, UserName);
                    TempData["Message"] = "Modificado Correctamente";
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("error", ex.Message);
            }

            return View();
        }

        [CustomAuthorize("006")]
        public ActionResult Delete(int id)
        {
           
            try
            {
                if (ModelState.IsValid)
                {
                    var Modulos = moduloContext.Select(new Dictionary<string, string> { { "Modulo_Id", id.ToString() } });
                    Modulos[0].Active = false;
                    moduloContext.Update(Modulos[0], User.Identity.Name);
                    TempData["Message"] = "Eliminado Correctamente";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("error", ex.Message);
            }

            return View();
        }
    }
}

seguridad/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using ET;
using seguridad.Filters;
namespace seguridad.Controllers
{
    [Authorize]
    public class RolesController : Controller
    {
        ContextRol DB_Rol = new ContextRol();
        private ModuloContext dbModulo = new ModuloContext();

        //
        // GET: /Roles/
        [CustomAuthorize("003")]
        public ActionResult Index(int id)
        {
            List<Rol> Roles = DB_Rol.Select(
                new Dictionary<string, string> { { "Modulo_Id", id.ToString() } }
                );
            if (TempData["Message"] != null)
            {
                ViewData["Message"] = TempData["Message"];
            }
            else
            {
                ViewData["Message"] = null;
            }
            ViewData["id"] = id;
            return View(Roles);
        }

        //
        // GET: /Roles/Details/5

        public ActionResult Details(int id = 0)
        {
            Rol webpages_roles = DB_Rol.Select(
                new Dictionary<string,string>{ {"RoleId",id.ToString()} }
                )[0];
            if (webpages_roles == null)
            {
                return HttpNotFound();
            }
            return View(webpages_roles);
        }

        //
        // GET: /Roles/Create

        public ActionResult Create(int id)
        {
            Rol role = new Rol();
            role.Modulo_Id = id;
            return View(role);
        }

        //
        // POST: /Roles/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rol rol)
        {
            var UserName = User.Identity.Name;
            if (ModelState.IsValid)
            {
                DB_Rol.Insert(rol, UserName);
                TempData["Message"] = "Guardado Correctamente";
                return RedirectToAction("Index",new { id = rol.Modulo_Id});
            }

            return View(rol);
        }

        //
        // GET: /Roles/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Rol rol = DB_Rol.Select(
                new Dictionary<string, string> { { "RoleId", id.ToString() } }
                )[0];
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        //
        // POST: /Roles/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Rol rol)
        {
            var UserName = User.Identity.Name;
            if (ModelState.IsValid)
            {
                if (rol.AccesoTotal == false)
                {
                    if (DB_Rol.RolesAccesoTotal("seguridad"))
                    {
                        DB_Rol.Update(rol, UserName);
                        TempData["Message"] = "Modificado Correctamente";
                        return RedirectToAction("Index", new { id = rol.Modulo_Id });
                    }
                    else
                    {
                        ModelState.AddModelError("error", "No puede eliminar rol de acceso total, debe haber obligatoriamente un rol con acceso total");
                        rol.AccesoTotal = true;
                        return View(rol);
                    }
                }
                else {
                    DB_Rol.Update(rol, UserName);
                    TempData["Message"] = "Modificado Correctamente";
                    return RedirectToAction("Index", new { id = rol.Modulo_Id });
                }
            }
            return View(rol);
        }

        //
        // GET: /Roles/Delete/5

        public ActionResult Delete(int id = 0)
        {
            string ModuloName = "";
            ModuloName=dbModulo.getModuloByRoleId(id);

            Rol webpages_roles = DB_Rol.Select(
                    new Dictionary<string, string> { { "RoleId", id.ToString() } }
                    )[0];

            if (DB_Rol.RolesAccesoTotal(ModuloName))
            {
                webpages_roles.Active = false;
                var UserName = User.Identity.Name;
                DB_Rol.Update(webpages_roles, UserName);
                TempData["Message"] = "Eliminado Correctamente";
                return RedirectToAction("Index", new { id = webpages_roles.Modulo_Id });
            }
            else {
                ModelState.AddModelError("error", "No puede eliminar el rol, debe haber obligatoriamente un rol con acceso total");

                List<Rol> Roles = DB_Rol.Select(
                new Dictionary<string, string> { { "Modulo_Id", webpages_roles.Modulo_Id.ToString() } }
                );
                if (TempData["Message"] != null)
                {
                    ViewData["Message"] = TempData["Message"];
                }
                else
                {
                    ViewData["Message"] = null;
                }

                return View("Index", Roles);
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

seguridad/Views/Modulo/Create.cshtml
@model ET.Modulo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
<div class="col-md-12 col-lg-10 col-lg-offset-1">
    <div class="panel">
        <div class="panel-heading">
            <hgroup class="title title-list">
                <h2>Nuevo Modulo</h2>
            </hgroup>
        </div>
        <div class="panel-body">

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="col-md-6">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Codigo)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Codigo)
                        @Html.ValidationMessageFor(model => model.Codigo)
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Nombre)
                    </div>
                    <div class="editor-field">
                        @Html.EditorFor(model => model.Nombre)
                        @Html.ValidationMessageFor(model => model.Nombre)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-3 col-md-offset-6">
                            <br />
                            @Html.ActionLink("Cancelar", "Index", "", new { @class = "form-control btn-info", @style = "text-align:center" })
                        </div>
                        <div class="col-md-3">
                            <br />
                            <input type="submit" value="Guardar" class="form-control btn-success" />
                        </div>
                    </div>
                </div>
            }

            @Html.ValidationMessage("error")
        </div>
    </div>
</div>
</div>

seguridad/Views/Modulo/Edit.cshtml
@model ET.Modulo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 col-lg-10 col-lg-offset-1">
        <div class="panel">
            <div class="panel-heading">
                <hgroup class="title title-list">
                    <h2>Editar Modulo</h2>
                </hgroup>
            </div>
            <div class="panel-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)



                    @Html.HiddenFor(model => model.Modulo_Id)
                    @Html.HiddenFor(model => model.Active)
                    @Html.HiddenFor(model => model.Create_User)
                    @Html.HiddenFor(model => model.Create_Date)

                    <div class="col-md-6">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Codigo)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Codigo)
                            @Html.ValidationMessageFor(model => model.Codigo)
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="editor-label">
                            @Html.LabelFor(model => model.Nombre)
                        </div>
                        <div class="editor-field">
                            @Html.EditorFor(model => model.Nombre)
                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-3 col-md-offset-6">
                                <br />
                                @Html.ActionLink("Cancelar", "Index", "", new { @class = "form-control btn-info", @style = "text-align:center" })
                            </div>
                            <div class="col-md-3">
                                <br />
                                <input type="submit" value="Guardar" class="form-control btn-success" />
                            </div>
                        </div>
                    </div>
                }
                @Html.ValidationMessage("error")
            </div>
        </div>
    </div>
</div>

seguridad/Views/Modulo/Index.cshtml
@model List<ET.Modulo>

@using seguridad.Filters

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Message"] != null)
{
    <script type="text/javascript">
                    window.onload = function () {
                        Swal.fire({
                          position: 'top-end',
                          icon: 'success',
                          title: '@TempData["Message"]',
                          showConfirmButton: false,
                          timer: 1500
                        })
                    };
    </script>
}

<div class="row">
    <div class="col-md-12 col-lg-10 col-lg-offset-1">
        <div class="panel">
            <div class="panel-heading">
                <hgroup class="title title-list">
                    <h2>Módulos</h2>
                    @if (FilterAuth.Authorize_User("005"))
                    {
                        @Html.ActionLink("Nuevo", "Create", "Roles", new { @class = "btn btn-info" })
                    }
                </hgroup>
            </div>
            <div class="panel-body">

                <table id="myTable" class="table table-responsive">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Codigo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.First().Nombre)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Codigo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>

                                @if (FilterAuth.Authorize_User("006"))
                                {
                                    @Html.ActionLink("Editar", "Edit", new { id = item.Modulo_Id })
                                }
                                @if (FilterAuth.Authorize_User("006"))
                                {
                                    <span>|</span>
                                    @*@Html.ActionLink("", "", new {@onclick = string.FormatshowAlert(@item.Modulo_Id)" })*@
                                    <a onclick="showAlert(@item.Modulo_Id)">Eliminar</a>
                               }
                                @if (FilterAuth.Authorize_User("002"))
                                {
                                    <span>|</span>
                                    @Html.ActionLink("Permisos", "Index", new { controller = "Permiso", id = item.Modulo_Id })
                                }
                                @if (FilterAuth.Authorize_User("003"))
                                {
                                    <span>|</span>
                                    @Html.ActionLink("Roles", "Index", new { controller = "Roles", id = item.Modulo_Id })
                                }
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#myTable').DataTable({
                "language": {
                    "url": "/Scripts/DataTables/lang/spanish.txt"
                }
            });

            //$(document).on('click', ".eliminar", function () {
            //    if (!confirm('¿Esta seguro que desea borrar este dato?')) {
            //        return false;
            //    }
            //});
        });

        function showAlert(id) {
            swal.fire({
                title: "Seguro que quiere eliminar el registro?",
                text: "Una vez aceptado este mensaje, no se puede revertir la operación!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, Eliminarlo!',
                cancelButtonText: 'Cancelar'
            })
                .then((result) => {
                    if (result.value) {

                        $.ajax({
                            type: "POST",
                            data: { 'id': id },
                            url: '@Url.Action("Delete","Modulo")',
                            success: function (data) {
                                swal.fire("Eliminado!", "El registro ha sido eliminado correctamente", "success")
                                .then((Ok) => {
                                     window.location= '@Url.Action("Index","Modulo")';
                                    })
                            },
                            error: function (data) {
                                swal.fire("ERROR!", "Ocurrió un error durante el proceso", "error");
                            }
                        });

                    } else {
                        swal.fire("Se ha cancelado el proceso de eliminar!");
                    }
                });
        };
    </script>
}